### ISSUE TITLE
Inter-Module Notifications via Non-Persistent (in-mem) Bus

### ISSUE THREAD

**Issue by ZarehD** [ardalis/RiverBooks#6]
Hi Steve. Given that MediatR is being used to publish inter-module notification events, it seems there's a risk that these in-memory notifications could be lost if the app crashes (or is shut-down) while the messages are in-flight. How should this be mitigated? Thanks.

**Comment by ardalis** [comment]
Exactly as you would mitigate if execution were mid method but hadn't returned yet when the server crashed in any other monolithic app.

**Comment by ZarehD** [comment]
So, I would normally use a transaction + try/catch block to mitigate that, but that would assume that published events are processed within the scope of that transaction. I guess I'm unsure whether that's the case.

Could you please clarify whether published events are processed in-line/in-flow such that they can participate in the ambient transaction, and if they throw an exception, whether that can/will bubble up to allow tx rollback?

Command-handler Example:
Start TX (i.e. TransactionScope);
try
  CRUD data;
  Publish event(s);  // they CRUD other data
  Commit TX;         // commits command AND event handler changes?
catch
  Roll-back TX;       // rolls back command AND event handler changes?

Could the event handlers participate in that ambient transaction? And, if they throw an exception, could/would that bubble up so the transaction can be rolled back?

**Comment by ZarehD** [comment]
It looks like **MediatR** uses `Task.WhenAll` to dispatch notifications, so the answer appears to be, yes, it's in-line/in-flow. Thanks for your help, Steve.
